### PR TITLE
Screenshots with new icons and neutral content

### PR DESCRIPTION
**Pull request by SteadyQuad**
2nd attempt: screenshots from emulator with neutral page

https://github.com/koreader/koreader/issues/7243

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-artwork/2)

### CODE REVIEW

**Comment by SteadyQuad** [comment]
https://github.com/koreader/koreader/issues/7243

**Comment by Frenzie** [comment]
@SteadyQuad You didn't give me permission to push to your branch. I'd like to shave off a few bytes on `pngquant -q 50 koreader-footnotes-thumbnail.png`.

**Comment by SteadyQuad** [comment]
@Frenzie I added you as a collaborator to SteadyQuad/koreader-artwork, is that what you need?

**Comment by Frenzie** [comment]
@SteadyQuad Normally when you make a PR you automatically allow commits from the owners of the repo you're PR-ing to (on the specific branch only). I think that's something you have to purposefully disable.

But I just need it to be a touch smaller with a quality around 50-60. I don't have time to push anything like that atm. :-)

**Comment by SteadyQuad** [comment]
I reduced koreader-footnotes-thumbnail.png in size further, but had to use FS dithering to keep the photo in the screenshot looking somewhat acceptable.

**Comment by SteadyQuad** [comment]
> @SteadyQuad Normally when you make a PR you automatically allow commits from the owners of the repo you're PR-ing to (on the specific branch only). I think that's something you have to purposefully disable.

Weird, I didn't know this, and didn't purposefully disable it either. Anyway, I pushed the new image myself.

**Comment by Frenzie** [comment]
Because you force-pushed it's unclear to me what if anything changed. Please try to avoid doing so as a rule of thumb. Anyway, thanks!

**Pull request merged**
