### PR TITLE
add screenshots with window decorations

### PR DESCRIPTION
**Pull request by pazos**
To be used in flathub.

Use landscape screenshots because portrait leaves empty room between them:

Sin nombre

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-artwork/3)

### CODE REVIEW

**Comment by Frenzie** [comment]
Could you use pngquant on them? It'll reduce the size a lot without any visual decrease in quality. (But it is lossy, mind you.)

Or maybe it'd make more sense on Flathub somehow if it's for Flathub?

**Comment by Frenzie** [comment]
Oh sorry, I didn't notice this wasn't the main repo. The pngquant remark stands though; the Flathub page will load faster. ;-)

**Comment by pazos** [comment]
> Oh sorry, I didn't notice this wasn't the main repo. The pngquant remark stands though; the Flathub page will load faster. ;-)

Actually pngquant make png larger :p

```bash
du -h *.png | grep framed
237K	koreader-dictionary-framed-fs8.png
228K	koreader-dictionary-framed.png
478K	koreader-footnotes-framed-fs8.png
460K	koreader-footnotes-framed.png
190K	koreader-menu-framed-fs8.png
184K	koreader-menu-framed.png
```

Do I need to add any argument to improve  the output?

**Comment by Frenzie** [comment]
What did your "minify" commit entail?

**Comment by pazos** [comment]
a web app, like https://squoosh.app/

**Comment by Frenzie** [comment]
They already use pngquant under the hood (or rather, <https://github.com/ImageOptim/libimagequant>). You can make it lossier by playing a bit with for example `pngquant --quality=65-80 [file]`.

400+ kB seems larger than I'd expected in any case.

**Comment by pazos** [comment]
> 400+ kB seems larger than I'd expected in any case.

It is. About 2x the other screenshots with the same resolution!. No idea why.

**Comment by Frenzie** [comment]
The other ones have big slabs of white, so it's not unexpected. Still, maybe a quick try with a simple JPEG?

**Comment by pazos** [comment]
jpg doesn't help without killing image quality.

What helped a bit, based or your "big slabs of white" comment, was to increase the font size a bit and use `pngquant --quality=65`

I hope it is good enough now :)

**Pull request merged**
